on:
  - push
  - pull_request

jobs:
  runs-on: ubuntu-latest

  steps:
    build:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.2
          run_install: true

      - name: Run typecheck
        run: pnpm typecheck

      - name: Build project
        run: pnpm build
